name: Export Godot
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Export via firebelley/godot-export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: .
          cache: true
          # Optional: export only certain presets by name (must match export_presets.cfg)
          # presets_to_export: |
          #   Web
          #   Linux/X11
          #   Windows Desktop
          # Optional: put builds under a custom folder
          # relative_export_path: exports
          # Optional: archive all exports (zip)
          # archive_output: true

      - name: Upload exports
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: exports/**  # or the default path the action used
