name: Export Godot (container)
on: [push, workflow_dispatch]

jobs:
  export:
    runs-on: ubuntu-latest
    container: abarichello/godot-ci:4.4.1
    steps:
      - uses: actions/checkout@v4
      - name: Export HTML5
        run: |
          mkdir -p build/web
          godot -v --headless --export-release "Web" build/web/index.html
      - uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
