name: Export Godot
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Export the project for all configured presets
      - name: Godot Export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip
          export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./         # folder containing project.godot
          cache: true                       # optional

      # Upload exported zips as build artifacts
      - name: Upload exports
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: exports/**
